name: Run Testbenches

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testbench: [tb_pwm, tb_circular_shift_register, tb_uart]  # Add your testbench names here

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup environment
      run: |
        sudo apt-get update

    - name: Install Icarus Verilog
      run: |
        sudo apt-get install -y iverilog

    - name: Run testbench
      run: |
        cd tb
        make ${{ matrix.testbench }} &
        wait

    - name: Cleanup
      run: |
        cd tb
        make clean
